#### This file is generated by sheet EOL_Data_Mainstream of file SWTDS_EOL_MazdaEndOfLine_Custlib.xlsm ####
####DON'T update manually###


package LIFT_PROJECT;


###############################
$VERSION = q$Revision: 1.2 $;
$HEADER = q$Header: config/Mapping_EOL.pm 1.0 11/25/2024 5:01:08 PM Nguyen Duy Khiem (MS/EAA43-VM) develop $;
###############################


$Defaults ->{'Mapping_EOL'}={
	'EOLmaxbyte' => 10,
	'byte_offset' => {
		'0' => {
			'7' => {
				'Name' => 'IsRightHandDriver',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['IsRightHandDriver'],
			},
			'6' => {
				'Name' => 'BT1FD',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['BT1FD'],
			},
			'5' => {
				'Name' => 'BT1FP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['BT1FP'],
			},
			'4' => {
				'Name' => 'BT1RD_BT1RP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['BT1RD', 'BT1RP'],
			},
			'3' => {
				'Name' => 'ALLFD',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['ALLFD'],
			},
			'2' => {
				'Name' => 'ALLFP',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['ALLFP'],
			},
			'1' => {
				'Name' => 'ALLRD_ALLRP',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['ALLRD', 'ALLRP'],
			},
			'0' => {
				'Name' => 'AB1FD',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['AB1FD'],
			},
		},
		'1' => {
			'7' => {
				'Name' => 'AB2FD',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['AB2FD'],
			},
			'6' => {
				'Name' => 'AB1FP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['AB1FP'],
			},
			'5' => {
				'Name' => 'AB2FP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['AB2FP'],
			},
			'4' => {
				'Name' => 'KA1FD',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['KA1FD'],
			},
			'3' => {
				'Name' => 'KA1FP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['KA1FP'],
			},
			'2' => {
				'Name' => 'CS1FD',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'CS1FP',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'AB1RD_AB1RP',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'2' => {
			'7' => {
				'Name' => 'IC1FD_IC1FP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['IC1FD', 'IC1FP'],
			},
			'6' => {
				'Name' => 'SA1FD_SA1FP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['SA1FD', 'SA1FP'],
			},
			'5' => {
				'Name' => 'FS1FD',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['FS1FD'],
			},
			'4' => {
				'Name' => 'FS1FP',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'3' => {
				'Name' => 'SA1RD_SA1RP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['SA1RD', 'SA1RP'],
			},
			'2' => {
				'Name' => 'UFSD_UFSP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['UFSD', 'UFSP'],
			},
			'1' => {
				'Name' => 'UFSD',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['UFSD'],
			},
			'0' => {
				'Name' => 'UFSC',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['UFSC'],
			},
		},
		'3' => {
			'7' => {
				'Name' => 'PASFD_PASFP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['PASFD', 'PASFP'],
			},
			'6' => {
				'Name' => 'PASMD_PASMP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['PASMD', 'PASMP'],
			},
			'5' => {
				'Name' => 'PPSFD_PPSFP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['PPSFD', 'PPSFP'],
			},
			'4' => {
				'Name' => 'ActiveSafety',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'3' => {
				'Name' => 'HOODRL',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'2' => {
				'Name' => 'HOODRR',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'PPABL_PPABR',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'PCS',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'4' => {
			'7' => {
				'Name' => 'PTS1_PTS2',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'COMess340and33E',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['CustIsCrashOutputMessage340and33ESupported'],
			},
			'5' => {
				'Name' => 'COMess04A',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['CustIsCrashOutputMessage04ASupported'],
			},
			'4' => {
				'Name' => 'ECall',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['ENSEcallSupported'],
			},
			'3' => {
				'Name' => 'DoorUnlock',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['ENSDoorUnlockSupported'],
			},
			'2' => {
				'Name' => 'HVCut',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['ENSHvCutSupported'],
			},
			'1' => {
				'Name' => 'ISODisposal',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'DSC',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'5' => {
			'7' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'OCS',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['CustIsOCSConfigured'],
			},
			'5' => {
				'Name' => 'PADIOFF',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['CustIsPADIOffSupported'],
			},
			'4' => {
				'Name' => 'PADION',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['CustIsPADIOnSupported'],
			},
			'3' => {
				'Name' => 'OCSCAN',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'2' => {
				'Name' => 'OCSKline',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['CustIsOccupantClassificationSystemKlineSupported'],
			},
			'1' => {
				'Name' => 'RSD',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'RSP',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'6' => {
			'7' => {
				'Name' => 'SPSFD',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['SPSFD'],
			},
			'6' => {
				'Name' => 'SPSFP',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'5' => {
				'Name' => 'BLFDType',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'4' => {
				'Name' => 'BLFPType',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'3' => {
				'Name' => 'BLRD_BLRP',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'2' => {
				'Name' => 'BLRC',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'OPSFP',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['OPSFP'],
			},
			'0' => {
				'Name' => 'SeatMatREAR',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'7' => {
			'7' => {
				'Name' => 'SeatBeltWIDRV',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'SeatBeltWIPGR',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'5' => {
				'Name' => 'SeatBeltWIREAR',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'4' => {
				'Name' => 'ParamA',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['CustIsAlgoParameterASupported'],
			},
			'3' => {
				'Name' => 'ParamB',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['CustIsAlgoParameterBSupported'],
			},
			'2' => {
				'Name' => 'ConnectorA',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'SecurityOEM1',
				'Variant' => {
					'Default' => {
						'Default'    => 1,
						'Restricted' => 1,
						'Update'     => 1,
						'Reverse'    => 'NA',
						},
				},
				'StaticBit' => ['CustIsSecurityAccessOEM1Supported'],
			},
			'0' => {
				'Name' => 'SecurityOEM2',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'8' => {
			'7' => {
				'Name' => 'SecurityOEM3',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'SecurityOEM4',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'5' => {
				'Name' => 'PADS1_PADS2',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['PADS1', 'PADS2'],
			},
			'4' => {
				'Name' => 'BLFDSource',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'3' => {
				'Name' => 'StaticRollover',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'2' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'9' => {
			'7' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'5' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'4' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'3' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'2' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'Reserved',
				'Variant' => {
					'Default' => {
						'Default'    => 0,
						'Restricted' => 0,
						'Update'     => 1,
						'Reverse'    => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
	},
},




$Defaults->{'EOL_CONFIG'} = {
	'IsRightHandDriver'					=>	'eol_sysvar::ENV_EOL_Bit_08',
	'BT1FD'					=>	'eol_sysvar::ENV_EOL_Bit_07',
	'BT1FP'					=>	'eol_sysvar::ENV_EOL_Bit_06',
	'BT1RD'					=>	'eol_sysvar::ENV_EOL_Bit_05',
	'BT1RP'					=>	'eol_sysvar::ENV_EOL_Bit_05',
	'ALLFD'					=>	'eol_sysvar::ENV_EOL_Bit_04',
	'ALLFP'					=>	'eol_sysvar::ENV_EOL_Bit_03',
	'ALLRD'					=>	'eol_sysvar::ENV_EOL_Bit_02',
	'ALLRP'					=>	'eol_sysvar::ENV_EOL_Bit_02',
	'AB1FD'					=>	'eol_sysvar::ENV_EOL_Bit_01',
	'AB2FD'					=>	'eol_sysvar::ENV_EOL_Bit_16',
	'AB1FP'					=>	'eol_sysvar::ENV_EOL_Bit_15',
	'AB2FP'					=>	'eol_sysvar::ENV_EOL_Bit_14',
	'KA1FD'					=>	'eol_sysvar::ENV_EOL_Bit_13',
	'KA1FP'					=>	'eol_sysvar::ENV_EOL_Bit_12',
	'CS1FD'					=>	'eol_sysvar::ENV_EOL_Bit_11',
	'CS1FP'					=>	'eol_sysvar::ENV_EOL_Bit_10',
	'AB1RD'					=>	'eol_sysvar::ENV_EOL_Bit_09',
	'AB1RP'					=>	'eol_sysvar::ENV_EOL_Bit_09',
	'IC1FD'					=>	'eol_sysvar::ENV_EOL_Bit_24',
	'IC1FP'					=>	'eol_sysvar::ENV_EOL_Bit_24',
	'SA1FD'					=>	'eol_sysvar::ENV_EOL_Bit_23',
	'SA1FP'					=>	'eol_sysvar::ENV_EOL_Bit_23',
	'FS1FD'					=>	'eol_sysvar::ENV_EOL_Bit_22',
	'FS1FP'					=>	'eol_sysvar::ENV_EOL_Bit_21',
	'SA1RD'					=>	'eol_sysvar::ENV_EOL_Bit_20',
	'SA1RP'					=>	'eol_sysvar::ENV_EOL_Bit_20',
	'UFSD'					=>	'eol_sysvar::ENV_EOL_Bit_19',
	'UFSP'					=>	'eol_sysvar::ENV_EOL_Bit_19',
	'UFSD'					=>	'eol_sysvar::ENV_EOL_Bit_18',
	'UFSC'					=>	'eol_sysvar::ENV_EOL_Bit_17',
	'PASFD'					=>	'eol_sysvar::ENV_EOL_Bit_32',
	'PASFP'					=>	'eol_sysvar::ENV_EOL_Bit_32',
	'PASMD'					=>	'eol_sysvar::ENV_EOL_Bit_31',
	'PASMP'					=>	'eol_sysvar::ENV_EOL_Bit_31',
	'PPSFD'					=>	'eol_sysvar::ENV_EOL_Bit_30',
	'PPSFP'					=>	'eol_sysvar::ENV_EOL_Bit_30',
	'ActiveSafety'					=>	'eol_sysvar::ENV_EOL_Bit_29',
	'HOODRL'					=>	'eol_sysvar::ENV_EOL_Bit_28',
	'HOODRR'					=>	'eol_sysvar::ENV_EOL_Bit_27',
	'PPABL'					=>	'eol_sysvar::ENV_EOL_Bit_26',
	'PPABR'					=>	'eol_sysvar::ENV_EOL_Bit_26',
	'PCS'					=>	'eol_sysvar::ENV_EOL_Bit_25',
	'PTS1'					=>	'eol_sysvar::ENV_EOL_Bit_40',
	'PTS2'					=>	'eol_sysvar::ENV_EOL_Bit_40',
	'COMess340and33E'					=>	'eol_sysvar::ENV_EOL_Bit_39',
	'COMess04A'					=>	'eol_sysvar::ENV_EOL_Bit_38',
	'ECall'					=>	'eol_sysvar::ENV_EOL_Bit_37',
	'DoorUnlock'					=>	'eol_sysvar::ENV_EOL_Bit_36',
	'HVCut'					=>	'eol_sysvar::ENV_EOL_Bit_35',
	'ISODisposal'					=>	'eol_sysvar::ENV_EOL_Bit_34',
	'DSC'					=>	'eol_sysvar::ENV_EOL_Bit_33',
	'OCS'					=>	'eol_sysvar::ENV_EOL_Bit_47',
	'PADIOFF'					=>	'eol_sysvar::ENV_EOL_Bit_46',
	'PADION'					=>	'eol_sysvar::ENV_EOL_Bit_45',
	'OCSCAN'					=>	'eol_sysvar::ENV_EOL_Bit_44',
	'OCSKline'					=>	'eol_sysvar::ENV_EOL_Bit_43',
	'RSD'					=>	'eol_sysvar::ENV_EOL_Bit_42',
	'RSP'					=>	'eol_sysvar::ENV_EOL_Bit_41',
	'SPSFD'					=>	'eol_sysvar::ENV_EOL_Bit_56',
	'SPSFP'					=>	'eol_sysvar::ENV_EOL_Bit_55',
	'BLFDType'					=>	'eol_sysvar::ENV_EOL_Bit_54',
	'BLFPType'					=>	'eol_sysvar::ENV_EOL_Bit_53',
	'BLRD'					=>	'eol_sysvar::ENV_EOL_Bit_52',
	'BLRP'					=>	'eol_sysvar::ENV_EOL_Bit_52',
	'BLRC'					=>	'eol_sysvar::ENV_EOL_Bit_51',
	'OPSFP'					=>	'eol_sysvar::ENV_EOL_Bit_50',
	'SeatMatREAR'					=>	'eol_sysvar::ENV_EOL_Bit_49',
	'SeatBeltWIDRV'					=>	'eol_sysvar::ENV_EOL_Bit_64',
	'SeatBeltWIPGR'					=>	'eol_sysvar::ENV_EOL_Bit_63',
	'SeatBeltWIREAR'					=>	'eol_sysvar::ENV_EOL_Bit_62',
	'ParamA'					=>	'eol_sysvar::ENV_EOL_Bit_61',
	'ParamB'					=>	'eol_sysvar::ENV_EOL_Bit_60',
	'ConnectorA'					=>	'eol_sysvar::ENV_EOL_Bit_59',
	'SecurityOEM1'					=>	'eol_sysvar::ENV_EOL_Bit_58',
	'SecurityOEM2'					=>	'eol_sysvar::ENV_EOL_Bit_57',
	'SecurityOEM3'					=>	'eol_sysvar::ENV_EOL_Bit_72',
	'SecurityOEM4'					=>	'eol_sysvar::ENV_EOL_Bit_71',
	'PADS1'					=>	'eol_sysvar::ENV_EOL_Bit_70',
	'PADS2'					=>	'eol_sysvar::ENV_EOL_Bit_70',
	'BLFDSource'					=>	'eol_sysvar::ENV_EOL_Bit_69',
	'StaticRollover'					=>	'eol_sysvar::ENV_EOL_Bit_68',
	'LoadDefault'        => 'eol_sysvar::ENV_TriggerToLoadDefaultEOL',
	'ReadEOL'            => 'eol_sysvar::ENV_TriggerToReadEOLButton',
	'WriteEOL'           => 'eol_sysvar::ENV_TriggerToWriteEOLButton',
	'Security_Access'    => 'eol_sysvar::ENV_TriggerToRequestSeed',
	'VariantValue'       => 'eol_sysvar::ENV_VariantValue',
	'VIN'			=> 'Write_VIN_TVV::VIN_number',
	'TVV'			=> 'Write_VIN_TVV::TVV_number',
	#Variant Code in EOL panel
	'Default' => '0',
},


#EOF
1;
