#### This file is generated by the Device mapping creator tool ####
#### Can be edited manually! ####

package LIFT_PROJECT;

##########################################################
$VERSION = q$Revision: 2.0 $;
$HEADER  = q$Header: config/Mapping_DEVICE.pm 2.0 11/10/24 Ly Kim Nguyen Ban (MS/EAA43-VM) (LKY81HC) develop  $;
##########################################################

$Defaults->{"Mapping_DEVICE"} = {

	#'label' --> give a label corresponding to the device
	#'type' --> type can be any of these: 'hall', 'mech' or 'resistive'
	'BLFP' => {
		'label'           => 'Buckle switch Passenger',
		'type'            => 'mech',
		'PositionA'       => '100',                       #Ohm
		'PositionB'       => '1000',                      #Ohm
		'STATE_INIT'      => '0x01',
		'STATE_POSITIONA' => '0x00',                      #Belt Not Used
		'STATE_POSITIONB' => '0x01',                      #Belt Used

		'State_PD'     => 'rb_swm_SwitchInfo_ast(3).PositionFiltered_en',
		'Status_PD'    => 'rb_swm_SwitchInfo_ast(3).StatusFiltered_en',
		'ExtStatus_PD' => 'rb_swm_SwitchInfo_ast(3).ExtStatusFiltered_en',
		'FaultFlag_PD' => 'rb_swma_AsicChannelData_ast(0)(0).FaultFlags_u8',
	},
	'PADS1' => {
		'label'     => 'Passenger Airbag Deactivation Switch 1',
		'type'      => 'mech',
		'PositionA' => '1000',                                     #Ohm
		'PositionB' => '100',                                      #Ohm

		'State_PD'     => 'rb_swm_SwitchInfo_ast(0).PositionFiltered_en',
		'Status_PD'    => 'rb_swm_SwitchInfo_ast(0).StatusFiltered_en',
		'ExtStatus_PD' => 'rb_swm_SwitchInfo_ast(0).ExtStatusFiltered_en',
		'FaultFlag_PD' => 'rb_swma_AsicChannelData_ast(0)(6).FaultFlags_u8',
	},
	'PADS2' => {
		'label'     => 'Passenger Airbag Deactivation Switch 1',
		'type'      => 'mech',
		'PositionA' => '100',                                      #Ohm
		'PositionB' => '1000',                                     #Ohm

		'State_PD'     => 'rb_swm_SwitchInfo_ast(1).PositionFiltered_en',
		'Status_PD'    => 'rb_swm_SwitchInfo_ast(1).StatusFiltered_en',
		'ExtStatus_PD' => 'rb_swm_SwitchInfo_ast(1).ExtStatusFiltered_en',
		'FaultFlag_PD' => 'rb_swma_AsicChannelData_ast(0)(2).FaultFlags_u8',
	},
	'SPSFD' => {
		'label'           => 'SeatTrackPositionSensorDriver',
		'type'            => 'hall',
		'positionA'       => '5',                                  #mA
		'positionB'       => '15',                                 #mA
		'Undefined'       => '8',                                  #mA
		'STATE_INIT'      => '0x01',
		'STATE_FAULT'     => '0x00',
		'STATE_POSITIONA' => '0x00',
		'STATE_POSITIONB' => '0x01',

		'State_PD'     => 'rb_swm_SwitchInfo_ast(4).PositionFiltered_en',
		'Status_PD'    => 'rb_swm_SwitchInfo_ast(4).StatusFiltered_en',
		'ExtStatus_PD' => 'rb_swm_SwitchInfo_ast(4).ExtStatusFiltered_en',
		'FaultFlag_PD' => 'rb_swma_AsicChannelData_ast(0)(9).FaultFlags_u8',

		'DataValueTable_SwitchStates_PD' => {
			'STATE_POSITIONA' => 0x0,
			'STATE_POSITIONB' => 0x1,

			'STATUS_VALID'   => 0x01,
			'STATUS_DEFAULT' => 0x01,
			'STATUS_FAULT'   => 0x02,
			'STATUS_INIT'    => 0x00,

			'EXTSTATUS_VALID'             => 0x00,
			'EXTSTATUS_FAULT'             => 0x01,
			'EXTSTATUS_NOTPRESENT'        => 0x02,
			'EXTSTATUS_INIT'              => 0x03,
			'EXTSTATUS_NOTCONFVALID'      => 0x04,
			'EXTSTATUS_NOTCONFFAULT'      => 0x05,
			'EXTSTATUS_NOTCONFNOTPRESENT' => 0x06,
			'EXTSTATUS_NOTCONFINIT'       => 0x07,
			'EXTSTATUS_NOTMONITORED'      => 0x08,

		},
	},

	#	This config is commented by default. Uncomment if use it
	'OPSFP' => {
				 'label'           => 'OPSFP',
				 'type'            => 'mech',
				 'STATE_INIT'      => '0x01',
				 'STATE_POSITIONA' => '0x02',    #Unoccupied
				 'STATE_POSITIONB' => '0x01',    #Occupied
				                                 #Switch states/values to be set (current in mA or resistance in ohm)
				 'Undefined'       => '',
				 'PositionA'       => '1000',    #Ohm
				 'PositionB'       => '100',     #Ohm
	},

	# ADD new for J30 Start
	'DBNA' => {
		'label' => 'ConnectorLockA',
		'type'  => 'mech',

		#Switch states/values to be set (current in mA or resistance in ohm)
		'Undefined' => '',
	},

	'DBNB' => {
		'label' => 'ConnectorLockB',
		'type'  => 'mech',

		#Switch states/values to be set (current in mA or resistance in ohm)
		'Undefined' => '',
	},

	'DBNC' => {
		'label' => 'ConnectorLockC',
		'type'  => 'mech',

		#Switch states/values to be set (current in mA or resistance in ohm)
		'Undefined' => '',
	},

	# ADD new for J30 End

	'Thresholds' => {    #Thresholds for each band

		'Switch_hall' => {    #current in mA
						   'Min'                    => '',
						   'ToleranceLow'           => '',
						   'Low'                    => '',
						   'ToleranceLowUndefined'  => '',
						   'LowUndefined'           => '',
						   'ToleranceUndefinedHigh' => '',
						   'UndefinedHigh'          => '',
						   'ToleranceHigh'          => '',
						   'High'                   => '',
						   'Max'                    => '',
		},

		'Switch_resistive' => {    #resistance in ohm
								'Min'                    => '',
								'ToleranceLow'           => '',
								'Low'                    => '',
								'ToleranceLowUndefined'  => '',
								'LowUndefined'           => '',
								'ToleranceUndefinedHigh' => '',
								'UndefinedHigh'          => '',
								'ToleranceHigh'          => '',
								'High'                   => '',
								'Max'                    => '',
		},

		'Squib' => {    #resistance in ohm
					 'Min'           => '',
					 'ToleranceLow'  => '',
					 'Low'           => '',
					 'ToleranceHigh' => '',
					 'High'          => '',
					 'Max'           => '',
		},
	},

};

$Defaults->{'TSG4'} = {

	'General' => {

		# CAN settings will be overwritten form testbench config settings
		'MaxVoltage' => 20,
	},

	'BELT_LOCKS' => {
		'BL20_Default'         => '100',
		'BL20_Name'            => 'BLFP',
		'BL20_Unit'            => 'R',
		'BL20_state_unbuckled' => '100',
		'BL20_state_PositionA' => '100',
		'BL20_state_buckled'   => '1000',
		'BL20_state_PositionB' => '1000',

		'BL19_Default'         => '100',
		'BL19_Name'            => 'BLFD',
		'BL19_Unit'            => 'R',
		'BL19_state_unbuckled' => '100',
		'BL19_state_PositionA' => '100',
		'BL19_state_buckled'   => '1000',
		'BL19_state_PositionB' => '1000',

		'BL21_Default'           => '15',
		'BL21_Name'              => 'SPSFD',
		'BL21_Unit'              => 'I',
		'BL21_state_Rearward'    => '5',
		'BL21_state_Forward'     => '15',
		'BL21_state_NotForemost' => '5',
		'BL21_state_Foremost'    => '15',
		'BL21_state_Undefined'   => '8',
		'BL21_state_PositionA'   => '5',
		'BL21_state_PositionB'   => '15',

		# Important: Please connect the PADS- of PADS1 and PADS2 to GND of TSG4.
		'BL26_Default'         => 'not_connected',    # init value = position A
		'BL26_Name'            => 'PADS1',            # mechanical switch type 2, posB < threshold < posA
		'BL26_Unit'            => 'R',
		'BL26_state_Default'   => '1000',
		'BL26_state_PositionA' => '1000',
		'BL26_state_PositionB' => '100',

		'BL27_Default'         => 'not_connected',    # init value = position A
		'BL27_Name'            => 'PADS2',            # mechanical switch type 3, posA < threshold < posB
		'BL27_Unit'            => 'R',		
		'BL27_state_Default'   => '100',
		'BL27_state_PositionA' => '100',
		'BL27_state_PositionB' => '1000',

		# 'BL25_Default'            	=> '1000',	# Type: mechanical 1, Position B < Thresholds < Position A
		'BL25_Default'          => 'not_connected',    #	This will not be connected by TSG4_InitHW
		'BL25_Name'             => 'OPSFP',
		'BL25_Unit'             => 'R',
		'BL25_state_occupied'   => '100',
		'BL25_state_PositionB'  => '100',
		'BL25_state_unoccupied' => '1000',
		'BL25_state_PositionA'  => '1000',

		# new adder
		'BL28_Default'         => '500',               #mechanical switch4: unbuckled A < 3.9V, buckled B >=3.9
		'BL28_Name'            => 'DBNA',
		'BL28_Unit'            => 'R',
		'BL28_state_unbuckled' => '500',
		'BL28_state_PositionA' => '500',
		'BL28_state_buckled'   => '100',
		'BL28_state_PositionB' => '100',

		'BL29_Default'         => '500',
		'BL29_Name'            => 'DBNB',
		'BL29_Unit'            => 'R',
		'BL29_state_unbuckled' => '500',
		'BL29_state_PositionA' => '500',
		'BL29_state_buckled'   => '100',
		'BL29_state_PositionB' => '100',

		'BL30_Default'         => '500',
		'BL30_Name'            => 'DBNC',
		'BL30_Unit'            => 'R',
		'BL30_state_unbuckled' => '500',
		'BL30_state_PositionA' => '500',
		'BL30_state_buckled'   => '100',
		'BL30_state_PositionB' => '100',
	},

	'CAN_FR' => {
				  'CF1_Name' => 'CAN1',
				  'CF2_Name' => 'CAN2',
	},
	'PAS_LINES' => {
					 'PAS_3_1_Name'  => 'UFSD',
					 'PAS_4_1_Name'  => 'UFSP',
					 'PAS_6_1_Name'  => 'UFSC',
					 'PAS_7_1_Name'  => 'PASFD',
					 'PAS_8_1_Name'  => 'PASFP',
					 'PAS_9_1_Name'  => 'PASMD',
					 'PAS_10_1_Name' => 'PASMP',
					 'PAS_11_1_Name' => 'PPSFD',
					 'PAS_12_1_Name' => 'PPSFP',
	},
	'K_LIN' => {
				 'KL3_Name'   => 'OCS',
				 'KL3_Type'   => 'Kline',
				 'KL3_output' => 'inverted',    #normal
	},
	'POWER_SUPPLY_LINES' => {
							  'PSL1_Default' => 'Ubat',
							  'PSL1_Name'    => 'UB1',
							  'PSL2_Default' => 'Ubat',
							  'PSL2_Name'    => 'UB2',       #U feed for CO
	},
	'SQUIBS' => {
		'SQ1_Default'  => '2.2',
		'SQ1_Name'     => 'AB1FD',
		'SQ2_Default'  => '2.2',
		'SQ2_Name'     => 'AB1FP',
		'SQ3_Default'  => '2.2',
		'SQ3_Name'     => 'AB2FD',
		'SQ4_Default'  => '2.2',
		'SQ4_Name'     => 'AB2FP',
		'SQ7_Default'  => '2.2',
		'SQ7_Name'     => 'BT1FD',
		'SQ8_Default'  => '2.2',
		'SQ8_Name'     => 'BT1FP',
		'SQ9_Default'  => '2.2',
		'SQ9_Name'     => 'BT1RD',
		'SQ10_Default' => '2.2',
		'SQ10_Name'    => 'BT1RP',
		'SQ13_Default' => '2.2',
		'SQ13_Name'    => 'IC1FD',
		'SQ14_Default' => '2.2',
		'SQ14_Name'    => 'IC1FP',
		'SQ15_Default' => '2.2',
		'SQ15_Name'    => 'KA1FD',
		'SQ16_Default' => '2.2',
		'SQ16_Name'    => 'KA1FP',
		'SQ19_Default' => '2.2',
		'SQ19_Name'    => 'SA1FD',
		'SQ20_Default' => '2.2',
		'SQ20_Name'    => 'SA1FP',
		'SQ21_Default' => '2.2',
		'SQ21_Name'    => 'SA1RD',
		'SQ22_Default' => '2.2',
		'SQ22_Name'    => 'SA1RP',
		'SQ23_Default' => 'not_connected',
		'SQ23_Name'    => 'FS1FD',

		# 'SQ30_Default' => '2.2',
		# 'SQ30_Name'    => 'ALLRD',
		# 'SQ31_Default' => '2.2',
		# 'SQ31_Name'    => 'ALLRP',

		# 'SQ25_Default'  => '2.2',
		# 'SQ25_Name'     => 'AB1RP',
		# 'SQ24_Default'  => '2.2',
		# 'SQ24_Name'     => 'AB1RDA',
		# 'SQ26_Default'  => '2.2',
		# 'SQ26_Name'     => 'AB1RDB',

		# 'SQ5_Default' => '2.2',
		# 'SQ5_Name'    => 'ALLFD',
		# 'SQ6_Default' => '2.2',
		# 'SQ6_Name'    => 'ALLFP',
	},

	'WARNING_LAMPS' => {    # uncomment for FLT testing
						 'WL1_1_Name' => 'AOutCrashOutput1',    #AO1 ENS3 'ENS3'	Door_Unlock
						 'WL1_2_Name' => 'AOutCrashOutput2',    #AO2 ENS2 'ENS2'	E_call
						 'WL1_3_Name' => 'AOutCrashOutput3',    #AO3 ENS1           HV_Cut
						 'WL1_4_Name' => 'AOutCrashOutput4',    #DISP
	},

	'EMPTY' => {},

};

$Defaults->{'Manitoo'} = {
	'SQUIBS' => {                              #All Squibs have been defined, no need to configure
				  'AB1FD' => { 'Default_value' => '2.2', },
				  'AB1FP' => { 'Default_value' => '2.2', },
				  'AB2FD' => { 'Default_value' => '2.2', },
				  'AB2FP' => { 'Default_value' => '2.2', },
				  'BT1FD' => { 'Default_value' => '2.2', },
				  'BT1FP' => { 'Default_value' => '2.2', },
				  'ALLFD' => { 'Default_value' => '2.2', },
				  'ALLFP' => { 'Default_value' => '2.2', },
				  'KA1FD' => { 'Default_value' => '2.2', },
				  'KA1FP' => { 'Default_value' => '2.2', },
				  'SA1FD' => { 'Default_value' => '2.2', },
				  'SA1FP' => { 'Default_value' => '2.2', },
				  'IC1FD' => { 'Default_value' => '2.2', },
				  'IC1FP' => { 'Default_value' => '2.2', },
				  'BT1RD' => { 'Default_value' => '2.2', },
				  'BT1RP' => { 'Default_value' => '2.2', },
				  'SA1RD' => { 'Default_value' => '2.2', },
				  'SA1RP' => { 'Default_value' => '2.2', },
				  'FS1FD' => { 'Default_value' => '2.2', },
				  'AB1RD' => { 'Default_value' => '2.2', },
				  'AB1RP' => { 'Default_value' => '2.2', },
				  'ALLRD' => { 'Default_value' => '2.2', },
				  'ALLRP' => { 'Default_value' => '2.2', },
	},

	'SWITCHES' => {    #base on SYC of each Project, define implemented switches are used

		'Switch_OPEN'  => { 'unbuckled', 'Open',  'PosA' },    # Open mean not short to GnD. Close mean Short to GnD
		'Switch_CLOSE' => { 'buckled',   'Close', 'PosB' },

		'PADS1' => {
					 'Unit'            => 'R',                          #R: Mech or Res Switch, I: Hall Switch
					 'State_Open'      => '800',
					 'State_Close'     => '400',
					 'State_Default'   => '400',
					 'State_Undefined' => '1500',
		},
		'PADS2' => {
					 'Unit'            => 'R',                          #R: Mech or Res Switch, I: Hall Switch
					 'State_Open'      => '400',
					 'State_Close'     => '800',
					 'State_Default'   => '400',
					 'State_Undefined' => '1500',
		},
		'BLFD' => {
					'Unit'            => 'I',
					'State_Unbuckled' => '5',
					'State_Buckled'   => '15',
					'State_Default'   => '15',
					'State_Undefined' => '13',
		},
		'BLFP' => {
					'Unit'            => 'I',
					'State_Unbuckled' => '5',
					'State_Buckled'   => '15',
					'State_Default'   => '15',
					'State_Undefined' => '13',
		},
		'OPSFP' => {
					 'Unit'            => 'R',
					 'State_Unbuckled' => '600',
					 'State_Buckled'   => '100',
					 'State_Default'   => '100',
					 'State_Undefined' => '300',
		},
		'SPSFD' => {
					 'Unit'            => 'I',
					 'State_Unbuckled' => '5',
					 'State_Buckled'   => '15',
					 'State_Default'   => '15',
					 'State_Undefined' => '8',
		},
		'SPSFP' => {
					 'Unit'            => 'I',
					 'State_Unbuckled' => '5',
					 'State_Buckled'   => '15',
					 'State_Default'   => '15',
					 'State_Undefined' => '8',
		},
		'DBNA' => {
					'Unit'            => 'R',
					'State_Unbuckled' => '100',
					'State_Buckled'   => '500',
					'State_Default'   => '500',
					'State_Undefined' => '400',
		},
		'DBNB' => {
					'Unit'            => 'R',
					'State_Unbuckled' => '100',
					'State_Buckled'   => '500',
					'State_Default'   => '500',
					'State_Undefined' => '400',
		},
		'DBNC' => {
					'Unit'            => 'R',
					'State_Unbuckled' => '100',
					'State_Buckled'   => '500',
					'State_Default'   => '500',
					'State_Undefined' => '400',
		},

	},
	'SENSORS' => {
		'UFSD'  => 'config',
		'UFSP'  => 'config',
		'UFSC'  => 'config',
		'PASFD' => 'config',
		'PASFP' => 'config',
		'PASMD' => 'config',
		'PASMP' => 'config',
		'PPSFD' => 'config',
		'PPSFP' => 'config',

	},
	'CAN' => { 'CAN1_Name' => 'Airbag_Bus', },

	'ANALOG_OUTPUTS' => {

		'AOutCrashOutput1' => {
								'type'    => 'LOW_SIDE_DRIVER',    #type and channel get from SYC
								'channel' => '1'
		},
		'AOutCrashOutput2' => {
								'type'    => 'HIGH_SIDE_DRIVER',    #type and channel get from SYC
								'channel' => '1'
		},
	},

};

$Defaults->{'DEVICE_CONFIG'} = {

	# Squibs
	'AB1FD' => 'AB1FD',
	'AB1FP' => 'AB1FP',
	'AB2FD' => 'AB2FD',
	'AB2FP' => 'AB2FP',
	'BT1FD' => 'BT1FD',
	'BT1FP' => 'BT1FP',
	'BT1RD' => 'BT1RD',
	'BT1RP' => 'BT1RP',
	'IC1FD' => 'IC1FD',
	'IC1FP' => 'IC1FP',
	'KA1FD' => 'KA1FD',
	'KA1FP' => 'KA1FP',
	'PPABL' => 'PPABL',
	'PPABR' => 'PPABR',
	'SA1FD' => 'SA1FD',
	'SA1FP' => 'SA1FP',
	'SA1RD' => 'SA1RD',
	'SA1RP' => 'SA1RP',
	'AB1RD' => 'AB1RD',
	'AB1RP' => 'AB1RP',
	'AB2RD' => 'AB2RD',
	'AB2RP' => 'AB2RP',
	'CS1FD' => 'CS1FD',
	'CS1FP' => 'CS1FP',
	'ALLRD' => 'ALLRD',
	'ALLRP' => 'ALLRP',
	'ALLFD' => 'ALLFD',
	'ALLFP' => 'ALLFP',
	'FS1FD' => 'FS1FD',

	'UFSD'  => 'UFSD',
	'UFSP'  => 'UFSP',
	'UFSC'  => 'UFSC',
	'PASFD' => 'PASFD',
	'PASFP' => 'PASFP',
	'PASMD' => 'PASMD',
	'PASMP' => 'PASMP',
	'PPSFD' => 'PPSFD',
	'PPSFP' => 'PPSFP',

	# Warning lamps
	'AOutCrashOutput1' => 'AOutCrashOutput1',
	'AOutCrashOutput2' => 'AOutCrashOutput2',
	'AOutCrashOutput3' => 'AOutCrashOutput3',
	'SeatBeltWIDRV'    => 'CustIsSeatBeltWarningIndicatorDriverSupported',
	'SeatBeltWIPGR'    => 'CustIsSeatBeltWarningIndicatorPassengerSupported',
	'SeatBeltWIREAR'   => 'CustIsSeatBeltWarningIndicatorRearSupported',

	# Switches
	'PADS1'          => 'PADS1',
	'PADS2'          => 'PADS2',
	'BLFD'           => 'BLFD',
	'BLFP'           => 'BLFP',
	'SPSFD'          => 'SPSFD',
	'SPSFP'          => 'SPSFP',
	'OPSFP'          => 'OPSFP',
	'ConnectorLockA' => 'ConnectorLockA',
	'ConnectorLockB' => 'ConnectorLockB',
	'ConnectorLockC' => 'ConnectorLockC',
	'RSD'            => 'RSD',
	'RSP'            => 'RSP',

	# Customer dummy device
	# ASICs
	'SystemAsic1'       => 'SystemAsic1',
	'SystemAsic2'       => 'SystemAsic2',
	'CentralSensorMain' => 'CentralSensorMain',
	'CentralSensorYaw'  => 'CentralSensorYaw',
	'CentralSensorRoll' => 'CentralSensorRoll',

	# Special Behaviour Bits
	'StaticRollover'            => 'DisableAlgoStaticRollover',
	'SpecBehItmDebugDelay'      => 'SpecBehItmDebugDelay',
	'DisableAlgoRollover'       => 'DisableAlgoRollover',
	'DisableAlgoStaticRollover' => 'DisableAlgoStaticRollover',
	'DisableAlgoPitch'          => 'DisableAlgoPitch',
	'DisableAlgoPep'            => 'DisableAlgoPep',
	'IsRightHandDriver'         => 'IsRightHandDriver',
	'OCS'                       => 'CustIsOCSConfigured',
	'OCSCAN'                    => 'CustIsOccupantClassificationSystemCANSupported',
	'OCSKline'                  => 'CustIsOccupantClassificationSystemKlineSupported',
	'CustDummySBit2'            => 'CustDummySBit2',
	'CustDummySBitN'            => 'CustDummySBitN',
	'ISODisposal'               => 'IsISODisposalSupported',
	'COMess340and33E'           => 'CustIsCrashOutputMessage340and33ESupported',
	'COMess04A'                 => 'CustIsCrashOutputMessage04ASupported',
	'ECall'                     => 'ENSEcallSupported',
	'DoorUnlock'                => 'ENSDoorUnlockSupported',
	'HVCut'                     => 'ENSHvCutSupported',
	'ActiveSafety'              => 'ActiveSafety',
	'VehDynamicSensor'          => 'CustIsVehicleDynamicSensorSupported',
	'ParamA'                    => 'CustIsAlgoParameterASupported',
	'ParamB'                    => 'CustIsAlgoParameterBSupported',
	'ConnectorA'                => 'ConnectorLockA',
	'SecurityOEM1'              => 'CustIsSecurityAccessOEM1Supported',
	'SecurityOEM2'              => 'CustIsSecurityAccessOEM2Supported',
	'SecurityOEM3'              => 'CustIsSecurityAccessOEM3Supported',
	'SecurityOEM4'              => 'CustIsSecurityAccessOEM4Supported',
	'RPMOnly'                   => 'CustIsEngineRPMOnly',

	#Section Activators
	'Dummy'              => 'Dummy',
	'CustFuelCutoffSys'  => 'CustFuelCutoffSys',
	'CustMazdaPlantMode' => 'CustMazdaPlantMode',
	'PADION'             => 'CustIsPADIOnSupported',
	'PADIOFF'            => 'CustIsPADIOffSupported',
	'CustDummyDBitN'     => 'CustDummyDBitN',
  },

  $Defaults->{'Coreassetconfig'} = {
	'SYC_device_map' => { 'SYC_VALIDATE' => 'YES', },

	'Aout' => {
				'Crash_Details' => {
									 'Crashcode'    => 'Single_EDR_Front_Inflatable;5',
									 'Crash_Faults' => [ rb_evm_CrashDetected_flt, rb_evm_FrontCrashDetected_flt, rb_edr_DataAreaFull_flt, rb_co_ThresholdOverFst_flt, rb_co_DoorUnlockAndEcallOutput_flt, rb_co_FuelCutoff_flt ],
				},
				'AOUT_CNS_DEVICE_MAP' => {
										   'AOutCrashOutput1' => 'CrashOutput1',
										   'AOutCrashOutput2' => 'CrashOutput2',
										   'AOutCrashOutput3' => 'CrashOutput3',
				},
	},

	'AOutCrashOutput1' => {
		'DriverType'    => 'LOW',
		'AOUT_ON_Fault' => 'NONE',    # Cannot be set with fault
		'AOUT_ON_Switch' => {
							  'Switch'   => [NONE],
							  'Position' => [NONE],     # Cannot be set with Switch by defaults it is PWM(Blinking continuously)
		},
		'AOUT_OFF_Switch' => {
							   'Switch'   => [NONE],
							   'Position' => [NONE],
		},
	},
	'AOutCrashOutput2' => {
		'DriverType'    => 'LOW',
		'AOUT_ON_Fault' => 'NONE',    # Cannot be set with fault
		'AOUT_ON_Switch' => {
							  'Switch'   => [NONE],
							  'Position' => [NONE],     # Cannot be set with Switch by defaults it is PWM(Blinking continuously)
		},
		'AOUT_OFF_Switch' => {
							   'Switch'   => [NONE],
							   'Position' => [NONE],
		},
	},
	'AOutCrashOutput3' => {
		'DriverType'    => 'LOW',
		'AOUT_ON_Fault' => 'NONE',    # Cannot be set with fault
		'AOUT_ON_Switch' => {
							  'Switch'   => [NONE],
							  'Position' => [NONE],     # Cannot be set with Switch by defaults it is PWM(Blinking continuously)
		},
		'AOUT_OFF_Switch' => {
							   'Switch'   => [NONE],
							   'Position' => [NONE],
		},
	},
  },

  $Defaults->{'CRASH_CONFIG'} = {

	'DOOR_UNLOCK' => {

		'EOL_Bit' => {
					   'DoorUnlock' => 'ENSDoorUnlockSupported',    #EOL bit DoorUnlock
		},
		'Static_Bit' => {
						  'AOutCrashOutput1' => 'AOutCrashOutput1',    #HW Crash ENS3
		  }

	},

	'E_CALL' => {
		'EOL_Bit' => {
					   'ECall' => 'ENSDoorUnlockSupported',         #EOL bit DoorUnlock
		},
		'Static_Bit' => {
						  'AOutCrashOutput2' => 'AOutCrashOutput2',    #HW Crash ENS3
		}
	},

	'HV_CUT' => {
		'EOL_Bit' => {
					   'HVCut'           => 'ENSHvCutSupported',                             #EOL bit HVCut
					   'COMess340and33E' => 'CustIsCrashOutputMessage340and33ESupported',    #EOL bit COMess340and33E
		},
		'Static_Bit' => {
						  'AOutCrashOutput3' => 'AOutCrashOutput3',                             #HW Crash ENS3
						  'CDTCrashOutput'   => 'CDTCrashOutput',
		}
	},
  },

  1;
