#### The EDID mappings should be generated by the EDR mapping creator tool ####
#### This file can be edited manually! ####

###This is mapping Snapshot/extended data for MAZDA AB12 Project###

package LIFT_PROJECT;

##########################################################
my $VERSION = q$Revision: 1.2 $;
my $HEADER  = q$Header: config/Mapping_CustomerData.pm 1.2 2020/08/19 15:24:45ICT Hoang Gia Nguyen (RBVH/EPS21) (HNN81HC) develop  $;
##########################################################

$Defaults->{'Mapping_SnapshotData'} = {
	'RAW_DATA_STRUCTURE' => {
		'HEADER_SECTION' => {
			'HEADER_SECTION_START_FROM_BYTE_INDEX' => '2',                                                                    # start counting bytes in response from 0,1,2,..
			'HEADER_DATA_POSITION'                 => 'FIXED_ORDER',                                                          # from mapping -> member key can be string or integer
			'HEADER_LIST'                          => [ 'DTC', 'StatusOfDTC', 'RecordNumber', 'RecordNumberOfIdentifiers' ]
		},

		'MEMBER_SECTION' => {
			'MEMBER_SECTION_START_FROM_BYTE_INDEX' => '8',                                                                    # start counting bytes in response from 0,1,2,..

			'MEMBER_DATA_POSITION'     => 'PRECEDING_IDENTIFIER',                                                             # ID followed by data -> only if member key is integer
			'MEMBER_ID_LENGTH_IN_BYTE' => '2',                                                                                # DID nbr is HIGHBYTE, LOWBYTE

			#            'MEMBER_DATA_POSITION' => 'BYTE_INDEX', # give 'StartByteIndex' in member definition
		},
	},

	'HEADER_DATA_DEFINITION' => {
		'DTC' => {
			'BytesPerDataSample'  => 3,
			'NumberOfDataSamples' => 1,
			'Description'         => '3 byte customer DTC',
		},
		'StatusOfDTC' => {
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Description'         => 'DTC status (8 bit)'
		},
		'RecordNumber' => {
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Description'         => 'Record number (corresponding to fault occurence)'
		},
		'RecordNumberOfIdentifiers' => {
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Description'         => 'Number of data elements in record'
		},
	},

	'MEMBER_DATA_DEFINITION' => {
		'GlobalRealTime' => {
			'Description'         => 'Global Real Time of the car',
			'ID'                  => 0xDD00,
			'BytesPerDataSample'  => 4,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'Global_Real_Time',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'mins',
			'Tolerance'           => 0,
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0xFFFFFFFF,
			},
		},
		'TotalDistance' => {
			'Description'         => 'Total Distance of the current cycle',
			'ID'                  => 0xDD01,
			'BytesPerDataSample'  => 3,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'Total_Distance',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'km',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0xFFFFFF,
			},
		},
		'MECUSupplyVoltage' => {
			'Description'         => 'Main ECU Voltage Supply',
			'ID'                  => 0xDD02,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'DataType'            => 'numeric',
			'Signal_name'         => 'MECU_supply_voltage',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'Vol',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0xFF,
			},
		},
		'OutsideTemperature' => {
			'Description'         => 'Outside Temperature',
			'ID'                  => 0xDD05,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'Out_car_temperature',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'deg',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0xFF,
			},
		},
		'PowerMode' => {    #
			'Description'         => 'Power Mode',
			'ID'                  => 0xDD06,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'PwMdeExtern_D_Actl',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => '',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0,
			},
		},
		'IG_OnTimer' => {    #
			'Description'         => 'IG_OnTimer',
			'ID'                  => 0xDCE1,
			'BytesPerDataSample'  => 2,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'IG_OnTimer',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'mins',
			'Tolerance'           => 0,
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0xFFFF,
			},
		},
		'StateOfCharge' => {    #
			'Description'         => 'State Of Charge',
			'ID'                  => 0xDCE2,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'SOC',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => '',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0,
			},
		},
		'Voltage' => {    #
			'Description'         => 'ECU voltage',
			'ID'                  => 0xD111,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'DataType'            => 'numeric',
			'Factor'              => 0.1,
			'Offset'              => 0,
			'Unit'                => 'V',
			'Tolerance'           => 10,
			'DataSource'          => 'Voltage',
		},
		'AccelPedalPosition' => {    #
			'Description'         => 'AccelPedalPosition',
			'ID'                  => 0x032B,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'AccelPedalPosition',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'NA',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0,
			},
		},
		'EngClnt' => {    #
			'Description'         => 'EngClnt',
			'ID'                  => 0xF405,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'EngClnt',
			'DataType'            => 'numeric',
			'Unit'                => 'degC',
			'Factor'              => 1,
			'Offset'              => 0,
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0,
			},
		},
		'EngineRotationSpeed' => {    #
			'Description'         => 'EngineRotationSpeed',
			'ID'                  => 0xF40C,
			'BytesPerDataSample'  => 2,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'EngineRotationSpeed',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'rpm',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0,
			},
		},
		'VehicleSpeed' => {    #
			'Description'         => 'VehicleSpeed',
			'ID'                  => 0xF40D,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'VehicleSpeed_signal',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'kph',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0,
			},
		},
		'ShiftPosition' => {
			'Description'         => 'ShiftPosition',
			'ID'                  => 0xDD1B,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'ShiftPosition',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'NA',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0xFF,
			},
		},
		'BrakeInputSwitchStatus' => {
			'Description'         => 'Brake Input Switch Status',
			'ID'                  => 0xDD17,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'BrakePedal',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'NA',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0,
			},
		},
		'EngRunTimer' => {
			'Description'         => 'EngRunTimer',
			'ID'                  => 0xF41F,
			'BytesPerDataSample'  => 2,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'EngRunTimer',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'secs',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0,
			},
		},
		'MotorRPM' => {
			'Description'         => 'MotorRPM_SS',
			'ID'                  => 0xDD08,
			'BytesPerDataSample'  => 2,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'MotorRPM_SS',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'rpm',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0,
			},
		},
		'StateOfCharge2' => {
			'Description'         => 'State Of Charge 2',
			'ID'                  => 0xDD09,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'SOC2_SS',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => '%',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0,
			},
		},
		'LastTimeFaultDetect' => {
			'Description'         => ' LastTimeFaultDetect',
			'ID'                  => 0xD960,
			'BytesPerDataSample'  => 4,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'Global_Real_Time',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'mins',
			'Tolerance'           => 0,
			'ToleranceType'       => 'relative',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0xFFFFFFFF,
			},
		},
		'LastTimeFaultClear' => {
			'Description'         => ' LastTimeFaultClear',
			'ID'                  => 0xD961,
			'BytesPerDataSample'  => 4,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'Global_Real_Time',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'mins',
			'Tolerance'           => 0,
			'ToleranceType'       => 'relative',
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0xFFFFFFFF,
			},
		},
		'FaultOccuranceTime' => {
			'Description'         => ' FaultOccuranceTime',
			'ID'                  => 0xD962,
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Variable_name'       => '',
			'Variable_type'       => '',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'time(s)',
			'Tolerance'           => 0,
			'DataSource'          => 'OccuranceCounter',
		},
		'FirstTimeFaultDetectKOC' => {
			'Description'         => ' FirstTimeFaultDetectKOC',
			'ID'                  => 0xD963,
			'BytesPerDataSample'  => 2,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'IG_OnTimer',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'sec',
			'Tolerance'           => 0,
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0xFFFF,
			},
		},
		'LastTimeFaultDetectKOC' => {
			'Description'         => ' LastTimeFaultDetectKOC',
			'ID'                  => 0xD9C5,
			'BytesPerDataSample'  => 2,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'IG_OnTimer',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'sec',
			'Tolerance'           => 0,
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0xFFFF,
			},
		},
		'LastTimeFaultClearKOC' => {
			'Description'         => ' LastTimeFaultClearKOC',
			'ID'                  => 0xD9C6,
			'BytesPerDataSample'  => 2,
			'NumberOfDataSamples' => 1,
			'Signal_name'         => 'IG_OnTimer',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'sec',
			'Tolerance'           => 0,
			'DataSource'          => 'COM_Signal',
			'DataValueTable'      => {
				'Init'    => 0,
				'Invalid' => 0xFFFF,
			},
		},
		'FirstTimeFaultDetectInternal' => {
			'Description'         => ' FirstTimeFaultDetectInternal',
			'ID'                  => 0xD9C7,
			'BytesPerDataSample'  => 4,
			'NumberOfDataSamples' => 1,
			'Variable_name'       => 'rb_tim_EcuOnTimeDataEe_st.PoOnTime_u32',
			'Variable_type'       => 'U32',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'sec(s)',
			'Tolerance'           => 60,
			'ToleranceType'       => 'absolute',
			'DataSource'          => 'PDVariable',
		},
		'LastTimeFaultDetectInternal' => {
			'Description'         => ' LastTimeFaultDetectInternal',
			'ID'                  => 0xD9C8,
			'BytesPerDataSample'  => 4,
			'NumberOfDataSamples' => 1,
			'Variable_name'       => 'rb_tim_EcuOnTimeDataEe_st.PoOnTime_u32',
			'Variable_type'       => 'U32',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'sec(s)',
			'Tolerance'           => 60,
			'ToleranceType'       => 'absolute',
			'DataSource'          => 'PDVariable',
		},
		'LastTimeFaultClearInternal' => {
			'Description'         => ' LastTimeFaultClearInternal',
			'ID'                  => 0xD9C9,
			'BytesPerDataSample'  => 4,
			'NumberOfDataSamples' => 1,
			'Variable_name'       => 'rb_tim_EcuOnTimeDataEe_st.PoOnTime_u32',
			'Variable_type'       => 'U32',
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'sec(s)',
			'Tolerance'           => 60,
			'ToleranceType'       => 'absolute',
			'DataSource'          => 'PDVariable',
		},
		'GpsDateTimeFirstTimeFaultDetect' => {
			'Description'         => 'GpsDateTimeFirstTimeFaultDetect',
			'ID'                  => 0xD966,
			'BytesPerDataSample'  => 6,
			'NumberOfDataSamples' => 1,
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'DataSource'          => 'COM_Signal_GpsTime_Cust',
			'DataValueTable'      => {
				'Init'    => 'FFFFFFFFFFFF',
				'Invalid' => 'FFFFFFFFFFFF',
			},
		},
		'GpsDateTimeFirstTimeFaultClear' => {
			'Description'         => 'GpsDateTimeFirstTimeFaultClear',
			'ID'                  => 0xD967,
			'BytesPerDataSample'  => 6,
			'NumberOfDataSamples' => 1,
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'DataSource'          => 'COM_Signal_GpsTime_Cust',
			'DataValueTable'      => {
				'Init'    => 'FFFFFFFFFFFF',
				'Invalid' => 'FFFFFFFFFFFF',
			},
		},
		'GpsDateTimeLastTimeFaultDetect' => {
			'Description'         => 'GpsDateTimeLastTimeFaultDetect',
			'ID'                  => 0xD968,
			'BytesPerDataSample'  => 6,
			'NumberOfDataSamples' => 1,
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'DataSource'          => 'COM_Signal_GpsTime_Cust',
			'DataValueTable'      => {
				'Init'    => 'FFFFFFFFFFFF',
				'Invalid' => 'FFFFFFFFFFFF',
			},
		},
		'GpsDateTimeLastTimeFaultClear' => {
			'Description'         => 'GpsDateTimeLastTimeFaultClear',
			'ID'                  => 0xD969,
			'BytesPerDataSample'  => 6,
			'NumberOfDataSamples' => 1,
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'DataSource'          => 'COM_Signal_GpsTime_Cust',
			'DataValueTable'      => {
				'Init'    => 'FFFFFFFFFFFF',
				'Invalid' => 'FFFFFFFFFFFF',
			},
		},
		'ExtraDataFirstTimeFaultDetect' => {
			'Description'         => 'ExtraDataFirstTimeFaultDetect',
			'ID'                  => 0xD990,
			'BytesPerDataSample'  => 6.5,
			'NumberOfDataSamples' => 2,
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'DataSource'          => 'Mazda_Extra_Data',
		},
		'ExtraDataFirstTimeFaultClear' => {
			'Description'         => 'ExtraDataFirstTimeFaultClear',
			'ID'                  => 0xD995,
			'BytesPerDataSample'  => 6.5,
			'NumberOfDataSamples' => 2,
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'DataSource'          => 'Mazda_Extra_Data',
		},
	},
};

$Defaults->{'Mapping_ExtendedData'} = {
	'RAW_DATA_STRUCTURE' => {
		'HEADER_SECTION' => {
			'HEADER_SECTION_START_FROM_BYTE_INDEX' => '2',                       # start counting bytes in response from 0,1,2,..
			'HEADER_DATA_POSITION'                 => 'FIXED_ORDER',             # from mapping -> member key can be string or integer
			'HEADER_LIST'                          => [ 'DTC', 'StatusOfDTC' ]
		},

		'MEMBER_SECTION' => {
			'MEMBER_SECTION_START_FROM_BYTE_INDEX' => '6',                       # start counting bytes in response from 0,1,2,..

			'MEMBER_DATA_POSITION'     => 'PRECEDING_IDENTIFIER',                # ID followed by data -> only if member key is integer
			'MEMBER_ID_LENGTH_IN_BYTE' => '1',                                   # DID nbr is HIGHBYTE, LOWBYTE

			#  'MEMBER_DATA_POSITION' => 'BYTE_INDEX', # give 'StartByteIndex' in member definition
		},
	},

	'HEADER_DATA_DEFINITION' => {
		'DTC' => {
			'BytesPerDataSample'  => 3,
			'NumberOfDataSamples' => 1,
			'Description'         => '3 byte customer DTC',
			'StartByteIndex'      => 2,
		},
		'StatusOfDTC' => {
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'Description'         => 'DTC status (8 bit)',
			'StartByteIndex'      => 5,
		},

	},

	#0x59 0x06 0x00 0x00 0x7F 0xAF 0x01 0x01 0x02 0x00 0x00 0x03 0x20

	'MEMBER_DATA_DEFINITION' => {
		'FaultDetectionCounter' => {
			'Description'         => 'Debounce counter',
			'BytesPerDataSample'  => 1,
			'NumberOfDataSamples' => 1,
			'ID'                  => 0x10,
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'DataSource'          => 'DebounceCounter',
		},
		'AgingCounter' => {
			'Description'         => 'Aging Counter',
			'BytesPerDataSample'  => 1,
			'ID'                  => 0x02,
			'NumberOfDataSamples' => 1,
			'DataType'            => 'numeric',
			'Factor'              => 1,
			'Offset'              => 0,
			'Unit'                => 'sec',
			'Tolerance'           => 0,
			'DataSource'          => 'AgingCounter',
		},
	},
};
1;
