#### This file is generated by sheet J30A24CY_Variants of file SWTDS_EOL_MazdaEndOfLine_Custlib.xlsm ####
####DON'T update manually###


package LIFT_PROJECT;


###############################
$VERSION = q$Revision: 1.2 $;
$HEADER = q$Header: config/Mapping_EOL.pm 1.0 11/3/2023 4:50:35 PM Ly Kim Nguyen Ban (MS/EAA43-CC) develop $;
###############################


$Defaults ->{'Mapping_EOL'}={
	'EOLmaxbyte' => 10,
	'byte_offset' => {
		'0' => {
			'7' => {
				'Name' => 'IsRightHandDriver',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['IsRightHandDriver'],
			},
			'6' => {
				'Name' => 'BT1FD',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'5' => {
				'Name' => 'BT1FP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'4' => {
				'Name' => 'BT1RD_BT1RP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'3' => {
				'Name' => 'ALLFD',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'2' => {
				'Name' => 'ALLFP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'ALLRD_ALLRP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'AB1FD',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'1' => {
			'7' => {
				'Name' => 'AB2FD',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'AB1FP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'5' => {
				'Name' => 'AB2FP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'4' => {
				'Name' => 'KA1FD',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'3' => {
				'Name' => 'KA1FP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'2' => {
				'Name' => 'CS1FD',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'CS1FP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'AB1RD_AB1RP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'2' => {
			'7' => {
				'Name' => 'IC1FD_IC1FP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'SA1FD_SA1FP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'5' => {
				'Name' => 'FS1FD',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'4' => {
				'Name' => 'FS1FP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'3' => {
				'Name' => 'SA1RD_SA1RP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'2' => {
				'Name' => 'UFSD_UFSP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'UFSD',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'UFSC',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'3' => {
			'7' => {
				'Name' => 'PASFD_PASFP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'PASMD_PASMP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'5' => {
				'Name' => 'PPSFD_PPSFP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'4' => {
				'Name' => 'ActiveSafety',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['ActiveSafety'],
			},
			'3' => {
				'Name' => 'HOODRL',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'2' => {
				'Name' => 'HOODRR',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'PPABL_PPABR',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'PCS',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'4' => {
			'7' => {
				'Name' => 'PTS1_PTS2',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'COMess340and33E',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsCrashOutputMessage340and33ESupported'],
			},
			'5' => {
				'Name' => 'COMess04A',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsCrashOutputMessage04ASupported'],
			},
			'4' => {
				'Name' => 'ECall',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['ENSEcallSupported'],
			},
			'3' => {
				'Name' => 'DoorUnlock',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['ENSDoorUnlockSupported'],
			},
			'2' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'ISODisposal',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['IsISODisposalSupported'],
			},
			'0' => {
				'Name' => 'VehDynamicSensor',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsVehicleDynamicSensorSupported'],
			},
		},
		'5' => {
			'7' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'OCS',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsOCSConfigured'],
			},
			'5' => {
				'Name' => 'PADIOFF',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsPADIOffSupported'],
			},
			'4' => {
				'Name' => 'PADION',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsPADIOnSupported'],
			},
			'3' => {
				'Name' => 'OCSCAN',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['CustIsOccupantClassificationSystemCANSupported'],
			},
			'2' => {
				'Name' => 'OCSKline',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsOccupantClassificationSystemKlineSupported'],
			},
			'1' => {
				'Name' => 'RSD',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'RSP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'6' => {
			'7' => {
				'Name' => 'SPSFD',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'SPSFP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'5' => {
				'Name' => 'BLFDType',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'4' => {
				'Name' => 'BLFPType',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'3' => {
				'Name' => 'BLRD_BLRP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'2' => {
				'Name' => 'BLRC',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'OPSFP',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'SeatMatREAR',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'7' => {
			'7' => {
				'Name' => 'SeatBeltWIDRV',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsSeatBeltWarningIndicatorDriverSupported'],
			},
			'6' => {
				'Name' => 'SeatBeltWIPGR',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsSeatBeltWarningIndicatorPassengerSupported'],
			},
			'5' => {
				'Name' => 'SeatBeltWIREAR',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsSeatBeltWarningIndicatorRearSupported'],
			},
			'4' => {
				'Name' => 'ParamA',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsAlgoParameterASupported'],
			},
			'3' => {
				'Name' => 'ParamB',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['CustIsAlgoParameterBSupported'],
			},
			'2' => {
				'Name' => 'ConnectorA',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['ConnectorLockA'],
			},
			'1' => {
				'Name' => 'SecurityOEM1',
				'Variant' => {
					'GEN_L' => {
						'Default' => 1,
						},
					'EU_R' => {
						'Default' => 1,
						},
					'EU_L' => {
						'Default' => 1,
						},
				},
				'StaticBit' => ['CustIsSecurityAccessOEM1Supported'],
			},
			'0' => {
				'Name' => 'SecurityOEM2',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['CustIsSecurityAccessOEM2Supported'],
			},
		},
		'8' => {
			'7' => {
				'Name' => 'SecurityOEM3',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['CustIsSecurityAccessOEM3Supported'],
			},
			'6' => {
				'Name' => 'SecurityOEM4',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['CustIsSecurityAccessOEM4Supported'],
			},
			'5' => {
				'Name' => 'PADS1_PADS2',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'4' => {
				'Name' => 'BLFDSource',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'3' => {
				'Name' => 'StaticRollover',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['DisableAlgoStaticRollover'],
			},
			'2' => {
				'Name' => 'RPMOnly',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['CustIsEngineRPMOnly'],
			},
			'1' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
		'9' => {
			'7' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'6' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'5' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'4' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'3' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'2' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'1' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
			'0' => {
				'Name' => 'Reserved',
				'Variant' => {
					'GEN_L' => {
						'Default' => 0,
						},
					'EU_R' => {
						'Default' => 0,
						},
					'EU_L' => {
						'Default' => 0,
						},
				},
				'StaticBit' => ['NA'],
			},
		},
	},
},




$Defaults->{'EOL_CONFIG'} = {
	'IsRightHandDriver'					=>	'eol_sysvar::ENV_EOL_Bit_08',
	'BT1FD'					=>	'eol_sysvar::ENV_EOL_Bit_07',
	'BT1FP'					=>	'eol_sysvar::ENV_EOL_Bit_06',
	'BT1RD'					=>	'eol_sysvar::ENV_EOL_Bit_05',
	'BT1RP'					=>	'eol_sysvar::ENV_EOL_Bit_05',
	'ALLFD'					=>	'eol_sysvar::ENV_EOL_Bit_04',
	'ALLFP'					=>	'eol_sysvar::ENV_EOL_Bit_03',
	'ALLRD'					=>	'eol_sysvar::ENV_EOL_Bit_02',
	'ALLRP'					=>	'eol_sysvar::ENV_EOL_Bit_02',
	'AB1FD'					=>	'eol_sysvar::ENV_EOL_Bit_01',
	'AB2FD'					=>	'eol_sysvar::ENV_EOL_Bit_16',
	'AB1FP'					=>	'eol_sysvar::ENV_EOL_Bit_15',
	'AB2FP'					=>	'eol_sysvar::ENV_EOL_Bit_14',
	'KA1FD'					=>	'eol_sysvar::ENV_EOL_Bit_13',
	'KA1FP'					=>	'eol_sysvar::ENV_EOL_Bit_12',
	'CS1FD'					=>	'eol_sysvar::ENV_EOL_Bit_11',
	'CS1FP'					=>	'eol_sysvar::ENV_EOL_Bit_10',
	'AB1RD'					=>	'eol_sysvar::ENV_EOL_Bit_09',
	'AB1RP'					=>	'eol_sysvar::ENV_EOL_Bit_09',
	'IC1FD'					=>	'eol_sysvar::ENV_EOL_Bit_24',
	'IC1FP'					=>	'eol_sysvar::ENV_EOL_Bit_24',
	'SA1FD'					=>	'eol_sysvar::ENV_EOL_Bit_23',
	'SA1FP'					=>	'eol_sysvar::ENV_EOL_Bit_23',
	'FS1FD'					=>	'eol_sysvar::ENV_EOL_Bit_22',
	'FS1FP'					=>	'eol_sysvar::ENV_EOL_Bit_21',
	'SA1RD'					=>	'eol_sysvar::ENV_EOL_Bit_20',
	'SA1RP'					=>	'eol_sysvar::ENV_EOL_Bit_20',
	'UFSD'					=>	'eol_sysvar::ENV_EOL_Bit_19',
	'UFSP'					=>	'eol_sysvar::ENV_EOL_Bit_19',
	'UFSD'					=>	'eol_sysvar::ENV_EOL_Bit_18',
	'UFSC'					=>	'eol_sysvar::ENV_EOL_Bit_17',
	'PASFD'					=>	'eol_sysvar::ENV_EOL_Bit_32',
	'PASFP'					=>	'eol_sysvar::ENV_EOL_Bit_32',
	'PASMD'					=>	'eol_sysvar::ENV_EOL_Bit_31',
	'PASMP'					=>	'eol_sysvar::ENV_EOL_Bit_31',
	'PPSFD'					=>	'eol_sysvar::ENV_EOL_Bit_30',
	'PPSFP'					=>	'eol_sysvar::ENV_EOL_Bit_30',
	'ActiveSafety'					=>	'eol_sysvar::ENV_EOL_Bit_29',
	'HOODRL'					=>	'eol_sysvar::ENV_EOL_Bit_28',
	'HOODRR'					=>	'eol_sysvar::ENV_EOL_Bit_27',
	'PPABL'					=>	'eol_sysvar::ENV_EOL_Bit_26',
	'PPABR'					=>	'eol_sysvar::ENV_EOL_Bit_26',
	'PCS'					=>	'eol_sysvar::ENV_EOL_Bit_25',
	'PTS1'					=>	'eol_sysvar::ENV_EOL_Bit_40',
	'PTS2'					=>	'eol_sysvar::ENV_EOL_Bit_40',
	'COMess340and33E'					=>	'eol_sysvar::ENV_EOL_Bit_39',
	'COMess04A'					=>	'eol_sysvar::ENV_EOL_Bit_38',
	'ECall'					=>	'eol_sysvar::ENV_EOL_Bit_37',
	'DoorUnlock'					=>	'eol_sysvar::ENV_EOL_Bit_36',
	'ISODisposal'					=>	'eol_sysvar::ENV_EOL_Bit_34',
	'VehDynamicSensor'					=>	'eol_sysvar::ENV_EOL_Bit_33',
	'OCS'					=>	'eol_sysvar::ENV_EOL_Bit_47',
	'PADIOFF'					=>	'eol_sysvar::ENV_EOL_Bit_46',
	'PADION'					=>	'eol_sysvar::ENV_EOL_Bit_45',
	'OCSCAN'					=>	'eol_sysvar::ENV_EOL_Bit_44',
	'OCSKline'					=>	'eol_sysvar::ENV_EOL_Bit_43',
	'RSD'					=>	'eol_sysvar::ENV_EOL_Bit_42',
	'RSP'					=>	'eol_sysvar::ENV_EOL_Bit_41',
	'SPSFD'					=>	'eol_sysvar::ENV_EOL_Bit_56',
	'SPSFP'					=>	'eol_sysvar::ENV_EOL_Bit_55',
	'BLFDType'					=>	'eol_sysvar::ENV_EOL_Bit_54',
	'BLFPType'					=>	'eol_sysvar::ENV_EOL_Bit_53',
	'BLRD'					=>	'eol_sysvar::ENV_EOL_Bit_52',
	'BLRP'					=>	'eol_sysvar::ENV_EOL_Bit_52',
	'BLRC'					=>	'eol_sysvar::ENV_EOL_Bit_51',
	'OPSFP'					=>	'eol_sysvar::ENV_EOL_Bit_50',
	'SeatMatREAR'					=>	'eol_sysvar::ENV_EOL_Bit_49',
	'SeatBeltWIDRV'					=>	'eol_sysvar::ENV_EOL_Bit_64',
	'SeatBeltWIPGR'					=>	'eol_sysvar::ENV_EOL_Bit_63',
	'SeatBeltWIREAR'					=>	'eol_sysvar::ENV_EOL_Bit_62',
	'ParamA'					=>	'eol_sysvar::ENV_EOL_Bit_61',
	'ParamB'					=>	'eol_sysvar::ENV_EOL_Bit_60',
	'ConnectorA'					=>	'eol_sysvar::ENV_EOL_Bit_59',
	'SecurityOEM1'					=>	'eol_sysvar::ENV_EOL_Bit_58',
	'SecurityOEM2'					=>	'eol_sysvar::ENV_EOL_Bit_57',
	'SecurityOEM3'					=>	'eol_sysvar::ENV_EOL_Bit_72',
	'SecurityOEM4'					=>	'eol_sysvar::ENV_EOL_Bit_71',
	'PADS1'					=>	'eol_sysvar::ENV_EOL_Bit_70',
	'PADS2'					=>	'eol_sysvar::ENV_EOL_Bit_70',
	'BLFDSource'					=>	'eol_sysvar::ENV_EOL_Bit_69',
	'StaticRollover'					=>	'eol_sysvar::ENV_EOL_Bit_68',
	'RPMOnly'					=>	'eol_sysvar::ENV_EOL_Bit_67',
	'LoadDefault'        => 'eol_sysvar::ENV_TriggerToLoadDefaultEOL',
	'ReadEOL'            => 'eol_sysvar::ENV_TriggerToReadEOLButton',
	'WriteEOL'           => 'eol_sysvar::ENV_TriggerToWriteEOLButton',
	'Security_Access'    => 'eol_sysvar::ENV_TriggerToRequestSeed',
	'VariantValue'       => 'eol_sysvar::ENV_VariantValue',
},


#EOF
1;
